---
- name: Pull Docker Image
  hosts: localhost
  remote_user: farmanahmed888
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "farmanahmed888/calculator:demo3"
        source: pull
        tag: "latest"

    - name: Start Docker
      service:
        name: docker
        state: started
      when: ansible_facts['os_family'] == "Debian"

    - name: Running container
      shell: /usr/local/bin/docker run -it -d --name calc farmanahmed888/demo3